# Generated by Django 4.2.4 on 2023-08-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentausuario',
            name='correo',
            field=models.EmailField(max_length=254),
        ),
    ]
