# Generated by Django 4.2.4 on 2023-08-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_orden_articuloorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('expiracion_mes', models.CharField(max_length=2)),
                ('expiracion_ano', models.CharField(max_length=2)),
                ('cvc', models.CharField(max_length=4)),
                ('guardar_tarjeta', models.BooleanField()),
            ],
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='carritoitem',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ArticuloOrden',
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
