# Generated by Django 4.2.4 on 2023-08-17 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pago_remove_carritoitem_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('expiracion_mes', models.PositiveIntegerField()),
                ('expiracion_ano', models.PositiveIntegerField()),
                ('cvc', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tarjeta_credito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tarjetacredito')),
            ],
        ),
    ]
